const SECTION_META = {
  product:["Household","Name, language and local time."],
  people:["Family members","Add people and choose their role and colour."],
  features:["Dashboard sections","Choose which experiences appear."],
  calendar:["Calendar & Ready","Calendars, colours, creation rights and preparation templates."],
  chores:["ChoreOps","Connect children to ChoreOps and set the parent destination."],
  football:["Football","Choose the household’s two Premier League favourites."],
  display:["Kiosk & photos","Starting view, tablet behaviour and family photo frame."],
  theme:["Appearance","Dashboard colours and shape."],
  home:["Home defaults","Starting room and control section."],
  rooms:["Rooms & devices","Map rooms, lights, heating, blinds, scenes and speakers."],
  media:["Music","Spotify and Music Assistant speaker mappings."],
  energy:["Energy","Electricity and gas smart-meter mappings."],
  weather:["Weather","Household weather source."],
  lists:["Lists","Preparation and shopping lists."],
  cleaning:["Cleaning","Robot vacuum and status mappings."],
  entry:["Security","Protected camera, alarm and garage mappings."],
  floorplan:["Floorplans","Protected floors, room hotspots and private assets."],
  school:["School","Protected Classroom or calendar fallback configuration."],
  location:["Location","Protected opt-in presence and map settings."]
};
const SECTION_ORDER = Object.keys(SECTION_META);
const PREMIER_LEAGUE_TEAMS = [
  ["ARS","Arsenal"],["AVL","Aston Villa"],["BOU","Bournemouth"],["BRE","Brentford"],
  ["BHA","Brighton & Hove Albion"],["BUR","Burnley"],["CHE","Chelsea"],["CRY","Crystal Palace"],
  ["EVE","Everton"],["FUL","Fulham"],["LEE","Leeds United"],["LIV","Liverpool"],
  ["MCI","Manchester City"],["MUN","Manchester United"],["NEW","Newcastle United"],["NFO","Nottingham Forest"],
  ["SUN","Sunderland"],["TOT","Tottenham Hotspur"],["WHU","West Ham United"],["WOL","Wolverhampton Wanderers"]
];
const state={bootstrap:null,original:null,config:null,section:"product",preview:null,dirty:false,floorplans:null};
const editor=document.querySelector("#editor");
const statusEl=document.querySelector("#status");
const nav=document.querySelector("#section-nav");
const reviewButton=document.querySelector("#review");
const discardButton=document.querySelector("#discard");
const dialog=document.querySelector("#review-dialog");

function clone(value){return structuredClone(value)}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function label(value){return String(value||"").replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase())}
function pathKey(path){return encodeURIComponent(JSON.stringify(path))}
function pathFrom(value){return JSON.parse(decodeURIComponent(value))}
function getAt(object,path){return path.reduce((value,key)=>value?.[key],object)}
function ensureParent(object,path){let entry=object;for(let index=0;index<path.length-1;index+=1){const key=path[index];if(entry[key]===undefined||entry[key]===null)entry[key]=typeof path[index+1]==="number"?[]:{};entry=entry[key]}return entry}
function setAt(object,path,value){ensureParent(object,path)[path.at(-1)]=value}
function deleteAt(object,path){const parent=path.slice(0,-1).reduce((entry,key)=>entry[key],object);Array.isArray(parent)?parent.splice(path.at(-1),1):delete parent[path.at(-1)]}
function resolveSchema(schema){if(!schema?.$ref)return schema;return schema.$ref.replace(/^#\//,"").split("/").reduce((value,key)=>value?.[key],state.bootstrap.schema)}
function inventoryDomain(schema){const resolved=resolveSchema(schema);const pattern=resolved?.pattern||"";const match=pattern.match(/^\^([a-z_]+)\\\./);return match?.[1]||null}
function defaultValue(schema){schema=resolveSchema(schema);if(schema.const!==undefined)return clone(schema.const);if(schema.default!==undefined)return clone(schema.default);if(schema.enum)return schema.enum[0];if(schema.type==="boolean")return false;if(schema.type==="integer"||schema.type==="number")return schema.minimum??0;if(schema.type==="array")return [];if(schema.type==="object"){const result={};for(const key of schema.required||[])result[key]=defaultValue(schema.properties?.[key]||{});return result}return ""}
function changed(){state.dirty=JSON.stringify(state.config)!==JSON.stringify(state.original);state.preview=null;reviewButton.disabled=!state.dirty;discardButton.disabled=!state.dirty;document.querySelector("#change-count").textContent=state.dirty?"Unsaved household changes":"No unsaved changes"}
function status(message,tone=""){statusEl.className=`notice ${tone?`is-${tone}`:""}`;statusEl.textContent=message}
function valueOptions(schema,current,path=[]){schema=resolveSchema(schema);if(schema.enum)return schema.enum.map(value=>[value,label(value)]);if(path[0]==="football"&&path[1]==="spotlight_team_codes"){const options=[...PREMIER_LEAGUE_TEAMS];if(current&&!options.some(([value])=>value===current))options.unshift([current,`${current} (currently configured)`]);return options}const domain=inventoryDomain(schema);if(!domain)return null;const options=(state.bootstrap.inventory.entities||[]).filter(entity=>entity.domain===domain).map(entity=>[entity.entity_id,entity.name||entity.original_name||entity.entity_id]);if(!options.length)return null;if(current&&!options.some(([value])=>value===current))options.unshift([current,`${current} (currently configured)`]);return options.sort((a,b)=>a[1].localeCompare(b[1]))}
function description(schema){return schema.description?`<small>${esc(schema.description)}</small>`:""}

function renderPrimitive(schema,value,path,name){schema=resolveSchema(schema);const key=pathKey(path);const readonly=schema.readOnly||schema.const!==undefined;const options=valueOptions(schema,value,path);if(schema.type==="boolean")return `<label class="field is-checkbox"><input data-path="${key}" type="checkbox" ${value?"checked":""} ${readonly?"disabled":""}><span>${esc(label(name))}</span>${description(schema)}</label>`;let type=(schema.type==="integer"||schema.type==="number")?"number":schema.pattern==="^#[0-9A-Fa-f]{6}$"?"color":"text";const limits=`${schema.minimum!==undefined?`min="${schema.minimum}"`:""} ${schema.maximum!==undefined?`max="${schema.maximum}"`:""} ${schema.maxLength?`maxlength="${schema.maxLength}"`:""}`;const control=options?`<select data-path="${key}" ${readonly?"disabled":""}>${options.map(([entry,text])=>`<option value="${esc(entry)}" ${String(entry)===String(value)?"selected":""}>${esc(text)}</option>`).join("")}</select>`:`<input data-path="${key}" type="${type}" value="${esc(value??"")}" ${limits} ${readonly?"disabled":""}>`;return `<label class="field"><span>${esc(label(name))}</span>${control}${description(schema)}</label>`}
function renderArray(schema,value,path,name){schema=resolveSchema(schema);const values=Array.isArray(value)?value:[];const itemSchema=resolveSchema(schema.items||{});return `<section class="array-editor"><div class="array-heading"><div><strong>${esc(label(name))}</strong>${description(schema)}</div><button type="button" class="add-button" data-add="${pathKey(path)}">Add</button></div><div class="array-items">${values.map((entry,index)=>`<div class="array-item"><button type="button" class="array-remove" data-remove="${pathKey([...path,index])}" aria-label="Remove">×</button>${renderNode(itemSchema,entry,[...path,index],`${label(name)} ${index+1}`)}</div>`).join("")||"<small>Nothing configured yet.</small>"}</div></section>`}
function renderObject(schema,value,path,name){schema=resolveSchema(schema);const entries=Object.entries(schema.properties||{}).filter(([key])=>!(path.length===0&&["schema_version","$schema"].includes(key)));return `<fieldset class="field-group"><legend>${esc(label(name))}</legend><div class="field-grid">${entries.map(([key,child])=>renderNode(child,value?.[key],[...path,key],key)).join("")}</div></fieldset>`}
function renderNode(schema,value,path,name){schema=resolveSchema(schema);if(schema.type==="array")return renderArray(schema,value,path,name);if(schema.type==="object"||schema.properties)return renderObject(schema,value||{},path,name);return renderPrimitive(schema,value,path,name)}

function renderFloorplanTools(){if(state.section!=="floorplan")return"";const assets=state.bootstrap.private_assets||{};return `<section class="floorplan-tools"><strong>Private floorplan files</strong><small>Upload both inert SVG files together. They are validated and deployed separately from household settings, and are never included in the public repository.</small><label>Ground floor SVG <input type="file" data-floorplan-file="ground-floor.svg" accept="image/svg+xml,.svg"></label><label>First floor SVG <input type="file" data-floorplan-file="first-floor.svg" accept="image/svg+xml,.svg"></label><div>${Object.entries(assets).map(([name,item])=>`<small>${esc(name)} · ${item.installed?`installed · ${esc(item.sha256.slice(0,12))}…`:"missing"}</small>`).join("<br>")}</div><div class="floorplan-tools-actions"><button type="button" class="secondary" data-floorplan-preview disabled>Validate both files</button></div></section>`}
function render(){const [title,copy]=SECTION_META[state.section];document.querySelector("#page-title").textContent=title;nav.querySelectorAll("button").forEach(button=>button.classList.toggle("is-active",button.dataset.section===state.section));const schema=state.bootstrap.schema.properties[state.section];const protectedSection=schema?.["x-protected"]===true;editor.innerHTML=`<div class="section-heading"><div><p>${protectedSection?"PROTECTED SETUP":"FAMILY SETTING"}</p><h2>${esc(title)}</h2><span>${esc(copy)}</span></div></div>${protectedSection?'<div class="protected-banner"><strong>Extra care required.</strong> Changes here can expose private data or operate protected household devices. They receive a separate warning before deployment.</div>':""}<div class="field-grid">${renderNode(schema,state.config[state.section],[state.section],state.section)}${renderFloorplanTools()}</div>`;bindEditor()}
function bindEditor(){editor.querySelectorAll("[data-path]").forEach(input=>input.addEventListener("change",()=>{const path=pathFrom(input.dataset.path);const schema=resolveSchema(path.reduce((entry,key)=>entry?.items&&typeof key==="number"?entry.items:entry?.properties?.[key],state.bootstrap.schema));let value=input.type==="checkbox"?input.checked:input.value;if(schema.type==="integer")value=Number.parseInt(value,10);if(schema.type==="number")value=Number(value);setAt(state.config,path,value);changed()}));editor.querySelectorAll("[data-add]").forEach(button=>button.addEventListener("click",()=>{const path=pathFrom(button.dataset.add);const schema=resolveSchema(path.reduce((entry,key)=>entry?.items&&typeof key==="number"?entry.items:entry?.properties?.[key],state.bootstrap.schema));let list=getAt(state.config,path);if(!Array.isArray(list)){list=[];setAt(state.config,path,list)}list.push(defaultValue(schema.items));changed();render()}));editor.querySelectorAll("[data-remove]").forEach(button=>button.addEventListener("click",()=>{deleteAt(state.config,pathFrom(button.dataset.remove));changed();render()}));editor.querySelectorAll("[data-floorplan-file]").forEach(input=>input.addEventListener("change",async()=>{state.floorplans=state.floorplans||{};const file=input.files?.[0];if(file)state.floorplans[input.dataset.floorplanFile]=await file.text();const ready=Object.keys(state.floorplans).length===2;editor.querySelector("[data-floorplan-preview]").disabled=!ready}));editor.querySelector("[data-floorplan-preview]")?.addEventListener("click",previewFloorplans)}

async function api(path,body){const response=await fetch(path,{method:body?"POST":"GET",headers:{"Content-Type":"application/json","X-Family-Dashboard-Admin":"1"},body:body?JSON.stringify(body):undefined});const payload=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok)throw new Error(payload.error||`HTTP ${response.status}`);return payload}
async function previewFloorplans(){try{status("Validating both private floorplans…","loading");const assets=Object.entries(state.floorplans).map(([filename,content])=>({filename,content}));const result=await api("api/admin/floorplans/preview",{assets});if(!confirm(`Both files are valid. Deploy private floorplans with set hash ${result.asset_set_hash.slice(0,12)}…?`)){status("Floorplan validation passed. No files were changed.","success");return}await api("api/admin/floorplans/deploy",{assets,expected_asset_set_hash:result.asset_set_hash,confirm:true});status("Both private floorplans were deployed successfully.","success")}catch(error){status(error.message,"error")}}
function renderReview(preview){const list=preview.changes.map(change=>`<div class="review-change"><strong>${esc(change.path)}</strong><code>${esc(JSON.stringify(change.before))}</code><span>→</span><code>${esc(JSON.stringify(change.after))}</code></div>`).join("");document.querySelector("#review-summary").innerHTML=`<div class="review-list"><p><strong>${preview.change_count}</strong> setting${preview.change_count===1?"":"s"} will change. The previous dashboard will be snapshotted first.</p>${list}</div>`;const ack=document.querySelector("#protected-ack");ack.hidden=!preview.requires_protected_acknowledgement;ack.querySelector("input").checked=false;dialog.showModal()}
async function preview(){try{reviewButton.disabled=true;status("Validating the complete household configuration…","loading");state.preview=await api("api/admin/preview",{config:state.config,expected_active_config_hash:state.bootstrap.active_config_hash});status("Validation passed. Review the exact changes before saving.","success");renderReview(state.preview)}catch(error){status(error.message,"error")}finally{reviewButton.disabled=!state.dirty}}
async function deploy(){if(!state.preview)return;const acknowledge=document.querySelector("#protected-ack input").checked;if(state.preview.requires_protected_acknowledgement&&!acknowledge){status("Confirm that you checked the protected mappings before saving.","error");return}try{document.querySelector("#deploy").disabled=true;const result=await api("api/admin/deploy",{config:state.config,expected_active_config_hash:state.bootstrap.active_config_hash,expected_config_hash:state.preview.config_hash,confirm:true,acknowledge_protected:acknowledge});dialog.close();state.original=clone(state.config);state.bootstrap.active_config_hash=result.resulting_config_hash;state.preview=null;changed();status(`Saved successfully. Rollback snapshot ${result.rollback_snapshot||"created"}. Refresh the dashboard resource to v0.12.0, then reload the tablet.`,"success")}catch(error){status(error.message,"error")}finally{document.querySelector("#deploy").disabled=false}}
function buildNavigation(){nav.innerHTML=SECTION_ORDER.filter(section=>state.bootstrap.schema.properties[section]).map(section=>`<button type="button" data-section="${section}" class="${state.bootstrap.schema.properties[section]["x-protected"]?"is-protected":""}">${esc(SECTION_META[section][0])}</button>`).join("");nav.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{state.section=button.dataset.section;render()}))}
async function start(){try{state.bootstrap=await api("api/admin/bootstrap");state.original=clone(state.bootstrap.config);state.config=clone(state.bootstrap.config);document.querySelector("#version").textContent=`v${state.bootstrap.version}`;document.querySelector("#user-name").textContent=state.bootstrap.user.name;buildNavigation();render();changed();status("Active configuration loaded. Nothing changes until you review and save.","success")}catch(error){status(error.message,"error")}}
reviewButton.addEventListener("click",preview);discardButton.addEventListener("click",()=>{state.config=clone(state.original);changed();render();status("Unsaved changes discarded.","success")});document.querySelector("#deploy").addEventListener("click",deploy);start();
